name       : python-snowballstemmer
version    : 1.2.1
release    : 3
source     :
    - https://pypi.python.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz : 919f26a68b2c17a7634da993d91339e288964f93c274f1343e3bbbe2096e1128
license    : BSD-2-Clause
component  : programming.python
summary    : Snowball stemming library collection for Python
description: |
    Snowball stemming library collection for Python
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
