name       : python-snowballstemmer
version    : 2.2.0
release    : 8
source     :
    - https://pypi.io/packages/source/s/snowballstemmer/snowballstemmer-2.2.0.tar.gz : 09b16deb8547d3412ad7b590689584cd0fe25ec8db3be37788be3810cbf19cb1
license    : BSD-2-Clause
component  : programming.python
summary    : Snowball stemming library collection for Python
description: |
    Snowball stemming library collection for Python
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
