name       : python-snowballstemmer
version    : 2.1.0
release    : 6
source     :
    - https://pypi.io/packages/source/s/snowballstemmer/snowballstemmer-2.1.0.tar.gz : e997baa4f2e9139951b6f4c631bad912dfd3c792467e2f03d7239464af90e914
license    : BSD-2-Clause
component  : programming.python
summary    : Snowball stemming library collection for Python
description: |
    Snowball stemming library collection for Python
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
